// Generates convex/seed/kits.ts and convex/seed/rubrics.ts from data/kits.json.
// Each rubric has 6 criteria in this fixed order:
//   1. Following instructions (universal)
//   2. Construction quality (universal)
//   3. Safety & material care (universal)
//   4. Concept understanding — <kit's concept> (kit-specific)
//   5. Scientific observation/exploration — <kit's name> (kit-specific, varies by category)
//   6. Communicating findings (universal)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const kits = JSON.parse(readFileSync("data/kits.json", "utf8"));

const UNIVERSAL = [
  {
    id: "following-instructions",
    label: "Following instructions",
    sub: "Procedural accuracy",
    c4: "Follows all steps in correct sequence independently, without reminders",
    c3: "Follows most steps correctly; needs one or two reminders",
    c2: "Follows steps with teacher guidance at several points",
    c1: "Unable to follow steps without continuous teacher support",
  },
  {
    id: "construction",
    label: "Construction quality",
    sub: "Build & technique",
    c4: "Builds neatly and accurately; final assembly works as intended on first try",
    c3: "Builds adequately; minor adjustments needed; final assembly works",
    c2: "Builds with significant teacher help; assembly partially works",
    c1: "Unable to complete the build without continuous help; assembly fails",
  },
  {
    id: "safety",
    label: "Safety & material care",
    sub: "Responsibility",
    c4: "Follows all safety rules; handles materials carefully; cleans workspace thoroughly",
    c3: "Follows safety rules with one reminder; cleans most of workspace",
    c2: "Follows safety rules with multiple reminders; partial clean-up",
    c1: "Disregards safety rules; leaves materials scattered",
  },
  {
    id: "communication",
    label: "Communicating findings",
    sub: "Verbal / written",
    c4: "Clearly communicates observations and conclusions using science vocabulary",
    c3: "Communicates findings adequately; uses some science vocabulary",
    c2: "Communicates in everyday language; limited science vocabulary",
    c1: "Cannot communicate findings clearly; very limited vocabulary",
  },
];

function kitSpecificCriteria(kit) {
  const concept = kit.concept || "the activity";
  const kitNameLower = (kit.kitName || "this kit").toLowerCase();
  const isExplorer = kit.category === "Explorer";

  return [
    {
      id: "concept-understanding",
      label: `Concept understanding — ${concept}`,
      sub: "Science concept",
      c4: `Accurately explains the ${concept} concept and connects it to a real-world application`,
      c3: `Explains the ${concept} concept with minor gaps`,
      c2: `Partially explains the ${concept} concept; needs prompting`,
      c1: `Cannot explain the ${concept} concept even with prompting`,
    },
    isExplorer
      ? {
          id: "observation",
          label: `Scientific observation — ${kitNameLower}`,
          sub: "Describing what happened",
          c4: "Accurately observes and describes what happened during the activity, unprompted",
          c3: "Describes most of what happened with minor prompting",
          c2: "Describes some observations; needs significant prompting",
          c1: "Unable to describe observations even with prompting",
        }
      : {
          id: "exploration",
          label: `Scientific exploration — ${kitNameLower}`,
          sub: "Investigating what could happen",
          c4: "Asks insightful questions and explores variations of the activity, unprompted",
          c3: "Explores variations of the activity with minor prompting",
          c2: "Tries one variation; needs significant prompting",
          c1: "Does not explore beyond following the given steps",
        },
  ];
}

function rubricFor(kit) {
  const [c4, c5] = kitSpecificCriteria(kit);
  return [UNIVERSAL[0], UNIVERSAL[1], UNIVERSAL[2], c4, c5, UNIVERSAL[3]];
}

mkdirSync("convex/seed", { recursive: true });

const kitsTs = `// AUTO-GENERATED by scripts/generate-rubrics.mjs. Do not edit by hand.
export type SeedKit = {
  kitNumber: number;
  concept: string;
  kitName: string;
  category: "Explorer" | "Discoverer";
  subject: string;
  grade: number;
  description: string;
};

export const SEED_KITS: SeedKit[] = ${JSON.stringify(kits, null, 2)};
`;
writeFileSync("convex/seed/kits.ts", kitsTs);

const rubricRows = kits.map((k) => ({
  kitNumber: k.kitNumber,
  category: k.category,
  kitName: k.kitName,
  criteria: rubricFor(k),
}));

const rubricsTs = `// AUTO-GENERATED by scripts/generate-rubrics.mjs. Do not edit by hand.
export type SeedRubricCriterion = {
  id: string;
  label: string;
  sub: string;
  c4: string;
  c3: string;
  c2: string;
  c1: string;
};

export type SeedRubric = {
  kitNumber: number;
  category: "Explorer" | "Discoverer";
  kitName: string;
  criteria: SeedRubricCriterion[];
};

export const SEED_RUBRICS: SeedRubric[] = ${JSON.stringify(rubricRows, null, 2)};
`;
writeFileSync("convex/seed/rubrics.ts", rubricsTs);

console.log(`Generated ${kits.length} kits + rubrics.`);
